train_events: ["hurricane-harvey","hurricane-michael", "mexico-earthquake",
              "palu-tsunami","socal-fire", "midwest-flooding"]
              
val_events:   ["hurricane-matthew", "guatemala-volcano"]
test_events:  ["hurricane-florence", "santa-rosa-wildfire"]

