train_events: ["hurricane-harvey","hurricane-michael",
               "midwest-flooding","santa-rosa-wildfire",
               "guatemala-volcano","palu-tsunami","socal-fire"]
val_events:   ["hurricane-matthew", "mexico-earthquake"]
test_events:  ["hurricane-florence"]

